title: Jame Connolly Scocial Club
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "/jcsc" # the subpath of your site, e.g. /blog
url: "cerees.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "./css/2016_style/img/jcsc_2_background.png"

social:
  name: JCSC Facebook
  link: "https://www.facebook.com/jamesconnollysocialclub/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/jamesconnollysocialclub/
#  - title: twitter
#    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty
